version: "3.1"
services:
  backend:
    image: quasimodo147/issue-tracker-springboot:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JDBC=jdbc:postgresql
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_PASSWORD=PASSWORD
      - DB_USER=postgres
    networks:
      - dinde

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: PASSWORD
    networks:
      - dinde
    volumes:
      - persist-pg

  # frontend not yet

networks:
  dinde:

volumes:
  persist-pg:
